### PR TITLE
1.13

### PR DESCRIPTION
**Pull request by kashike**

### CODE REVIEW

**Comment by Minecrell** [comment]
Is this coming from Forge/FML in 1.13 or is this just something you/we want to enforce starting with 1.13?

**Comment by ImMorpheus** [comment]
> Is this coming from Forge/FML in 1.13 or is this just something you/we want to enforce starting with 1.13?

https://github.com/MinecraftForge/MinecraftForge/commit/276d0c49c17c186789c875bd95b633ddb019d43a

**Comment by kashike** [comment]
After talking with @cpw he's agreed upon using `^[a-z][a-z0-9-_]{1,63}$` in Forge, and so it makes sense for us to adopt as well.

**Review by stephan-gh — APPROVED** [review]

**Review by gabizou — APPROVED** [review]

**Comment by liach** [comment]
Hmm, I think the pattern kashike used here differ from that in the commit referenced above.

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/040cc4bf16d2355733d9b78974c5083f5980bde2#diff-dab1ffbd14e4a1b395cc6c45e152ea9dR43 is the relevant commit.

**Review by liach — APPROVED** [review]

**Pull request merged**
